version: '3.4'

services:
  reasoner:
    environment:
      VIRTUAL_HOST: "reasoner.dev.devloed.com"
      LETSENCRYPT_HOST: "reasoner.dev.devloed.com"
      LETSENCRYPT_EMAIL: "support+lblod@devloed.com"
    networks:
      - proxy
      - default

networks:
  proxy:
    name: app-letsencrypt_default